/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline-variant": "#e0c0b1",
        "secondary-container": "#dfe0e0",
        "primary-container": "#f97316",
        "inverse-surface": "#2e3132",
        "secondary": "#5d5f5f",
        "on-secondary-fixed": "#1a1c1c",
        "on-background": "#191c1e",
        "surface-container": "#edeef0",
        "outline": "#8c7164",
        "error-container": "#ffdad6",
        "primary": "#9d4300",
        "primary-fixed": "#ffdbca",
        "surface-container-high": "#e7e8ea",
        "on-secondary-fixed-variant": "#454747",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#00a2f4",
        "tertiary-fixed": "#cde5ff",
        "on-secondary-container": "#616363",
        "on-error": "#ffffff",
        "surface-bright": "#f8f9fb",
        "primary-fixed-dim": "#ffb690",
        "on-primary-fixed": "#341100",
        "surface-tint": "#9d4300",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary-fixed-variant": "#004b74",
        "background": "#f8f9fb",
        "on-primary-container": "#582200",
        "tertiary": "#006398",
        "surface-dim": "#d9dadc",
        "on-surface": "#191c1e",
        "on-tertiary-fixed": "#001d32",
        "inverse-primary": "#ffb690",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#584237",
        "secondary-fixed": "#e2e2e2",
        "surface-container-low": "#f3f4f6",
        "on-tertiary-container": "#003554",
        "secondary-fixed-dim": "#c6c6c7",
        "on-secondary": "#ffffff",
        "surface": "#f8f9fb",
        "surface-container-highest": "#e1e2e4",
        "on-primary": "#ffffff",
        "surface-variant": "#e1e2e4",
        "on-primary-fixed-variant": "#783200",
        "tertiary-fixed-dim": "#93ccff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "base": "8px",
        "xl": "80px",
        "margin": "32px",
        "lg": "48px",
        "gutter": "24px",
        "md": "24px",
        "sm": "12px",
        "xs": "4px"
      },
      "fontFamily": {
        "button": ["Inter"],
        "h2": ["Be Vietnam Pro"],
        "h3": ["Be Vietnam Pro"],
        "h1": ["Be Vietnam Pro"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "button": ["16px", {"lineHeight": "1", "fontWeight": "600"}],
        "h2": ["32px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "h3": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "h1": ["48px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "label-md": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
